#!/bin/bash -x
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
echo BEGIN $(date '+%Y-%m-%d %H:%M:%S')

# install some base tools
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install curl unzip jq
# determine which cloud we are in and set some variables
if [[ $(sudo dmidecode -s bios-version) =~ .*\.amazon ]]
then
  echo "This is AWS"
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  VM_IP=${VM_IP}
elif [[ $(sudo dmidecode -s bios-version) =~ Google ]]
then
  echo "This is GCP"
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  VM_IP=${VM_IP}
else
  echo "This is Azure"
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  VM_IP=${VM_IP}
fi
sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes apt-transport-https ca-certificates curl unzip jq gnupg-agent software-properties-common awscli
sudo -i
sudo apt-get update

echo END $(date '+%Y-%m-%d %H:%M:%S')
