#!/bin/bash -x
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
echo BEGIN $(date '+%Y-%m-%d %H:%M:%S')

export PATH="$HOME/.local/bin:$PATH"

# install some base tools
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install curl unzip jq python3 python3-pip
# determine which cloud we are in and set some variables
if [[ $(sudo dmidecode -s bios-version) =~ .*\.amazon ]]
then
  echo "This is AWS"
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  VM_IP=$(curl -s 'https://api.ipify.org?format=text')
elif [[ $(sudo dmidecode -s bios-version) =~ Google ]]
then
  echo "This is GCP"
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  VM_IP=$(curl -s 'https://api.ipify.org?format=text')
else
  echo "This is Azure"
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  VM_IP=$(curl -s 'https://api.ipify.org?format=text')
fi
sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes apt-transport-https ca-certificates curl unzip jq gnupg-agent software-properties-common awscli
echo -e '\e[38;5;198m'"++++ Configure SSH to allow login with password"
sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
sudo systemctl reload ssh

pip install awxkit
pip install --target="$HOME/.local" awxkit
sudo pip install --target="$HOME/.local" awxkit

echo END $(date '+%Y-%m-%d %H:%M:%S')
